-- Supabase SQL Editor에서 실행하세요.
-- 이 설정은 GitHub Pages 같은 정적 사이트에서 전 세계 First Discovery와 랭킹을 저장하기 위한 예시입니다.
-- 공개 게임용이므로 개인정보를 저장하지 마세요.

create table if not exists public.discoveries (
  id bigint generated by default as identity primary key,
  element_id text not null unique,
  element_name text not null,
  emoji text,
  recipe_a text,
  recipe_b text,
  recipe_key text,
  player_id text not null,
  player_name text not null default '탐험가',
  created_at timestamptz not null default now()
);

create table if not exists public.rankings (
  player_id text primary key,
  player_name text not null default '탐험가',
  element_count integer not null default 0,
  craft_count integer not null default 0,
  first_count integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.discoveries enable row level security;
alter table public.rankings enable row level security;

-- 누구나 발견 목록을 읽을 수 있음
create policy "discoveries_select_all"
on public.discoveries for select
to anon
using (true);

-- 누구나 새 발견을 등록할 수 있음. element_id unique 때문에 첫 사람만 성공합니다.
create policy "discoveries_insert_anon"
on public.discoveries for insert
to anon
with check (
  length(element_id) between 1 and 80
  and length(element_name) between 1 and 80
  and length(player_id) between 6 and 80
  and length(player_name) between 1 and 18
);

-- 랭킹 읽기
create policy "rankings_select_all"
on public.rankings for select
to anon
using (true);

-- 랭킹 등록
create policy "rankings_insert_anon"
on public.rankings for insert
to anon
with check (
  length(player_id) between 6 and 80
  and length(player_name) between 1 and 18
  and element_count >= 0
  and craft_count >= 0
  and first_count >= 0
);

-- 랭킹 업데이트. 단순 공개 게임용 정책입니다.
create policy "rankings_update_anon"
on public.rankings for update
to anon
using (true)
with check (
  length(player_id) between 6 and 80
  and length(player_name) between 1 and 18
  and element_count >= 0
  and craft_count >= 0
  and first_count >= 0
);

create index if not exists discoveries_created_idx on public.discoveries (created_at desc);
create index if not exists rankings_score_idx on public.rankings (first_count desc, element_count desc, craft_count desc);
